name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.14"]
        uv-version: ["latest"]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    #container:
      #image: ubuntu:latest
      #options: --user root

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: bash .github/workflows/linux-dependencies-install.sh
          #apt install -y sudo
          #sudo apt update
          #sudo apt install -y libgirepository-2.0-dev gcc \
            #libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cairo pkg-config

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: echo "Windows wheels handle cairo dependencies automatically."

      - uses: astral-sh/setup-uv@v6
        with:
          version: ${{ matrix.uv-version }}
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with uv
        run: uv sync --locked --dev --group test

      - name: Install Pyrefly
        run: pip install pyrefly

      - uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: uv run pytest -v tests/
